"""Init

Revision ID: fa78684acfcd
Revises: 
Create Date: 2026-07-28 14:33:14.795653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa78684acfcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False, comment="A unique identifier for the user. It's a UUID type and is automatically generated by the database."),
    sa.Column('balance', sa.Numeric(precision=18, scale=2), server_default=sa.text('0'), nullable=False, comment="Balance of user's wallet"),
    sa.CheckConstraint('balance >= 0', name='ck_wallets_balance_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wallets')
    # ### end Alembic commands ###
