import uuid
from typing import TYPE_CHECKING

from sqlalchemy import UUID, String, text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from .base import Base

if TYPE_CHECKING:
    from backend.app.model.wallet import Wallet


class User(Base):

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="A unique identifier for the user. It's a UUID type and is automatically generated by the database.",
    )
    username: Mapped[str] = mapped_column(
        String(),
        nullable=False,
    )
    hashed_password: Mapped[str] = mapped_column(
        String(),
        nullable=False,
    )
    hashed_api_token: Mapped[str] = mapped_column(
        String(),
        nullable=False,
        unique=True,
        comment="SHA-256 hash of the opaque bearer token issued to the user at signup.",
    )

    wallet: Mapped["Wallet"] = relationship(
        back_populates="user",
        lazy="selectin",
    )
