import uuid
from decimal import Decimal

from sqlalchemy import CheckConstraint, Numeric, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column

from .base import Base


class Wallet(Base):
    __tablename__ = "wallets"
    __table_args__ = (
        CheckConstraint("balance >= 0", name="ck_wallets_balance_non_negative"),
    )

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
        comment="A unique identifier for the user. It's a UUID type and is automatically generated by the database.",
    )

    balance: Mapped[Decimal] = mapped_column(
        Numeric(18, 2),
        server_default=text("0"),
        comment="Balance of user's wallet"
    )
